# Welcome to Jekyll!

title: UI Kit
docs_version: 2.0
baseurl: ""
url: ""

markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-toc

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
